const products = [
  {
    id: 1,
    name: "XR de Marqués de Riscal 2015",
    description: "",
    tags: ["vino", "tinto"],
    image: "./vino_tinto_xr.jpeg",
    price: 10,
    comparePrice: 21.5,
    quantity: 2,
    urlComparePrice: "https://www.enbotella.com/vino/marques-de-riscal-xr/",
    available: true,
  },
  {
    id: 2,
    name: "XR de Marqués de Riscal 2016",
    description: "",
    tags: ["vino", "tinto"],
    image: "./vino_tinto_xr_2016.jpeg",
    price: 10,
    comparePrice: 21.5,
    quantity: 2,
    urlComparePrice: "https://www.enbotella.com/vino/marques-de-riscal-xr/",
    available: true,
  },
  {
    id: 3,
    name: "Lagar de robla Vintage",
    description: "",
    tags: ["vino", "tinto"],
    image: "./vino_tinto_lagar.jpeg",
    price: 1,
    comparePrice: 2.99,
    quantity: 1,
    urlComparePrice:
      "https://www.alcampo.es/compra-online/bebidas/vino-tinto/toro-bierzo-y-castillaleon/otros-castilla-leon/lagar-de-robla-vino-tinto-75-cl/p/33046",
    available: true,
  },
  {
    id: 4,
    name: "Ginebra MASTER MAKERS London Dry Gin 70 Cl.",
    description:
      "Master Makers es una ginebra elaborada en Galicia en auténtico alambique de cobre.",
    tags: ["ginebra"],
    image: "./master_makers_2019.jpeg",
    price: 10,
    comparePrice: 16.95,
    quantity: 3,
    urlComparePrice:
      "https://www.gulagalega.com/ginebra-ron-y-vodka/75-ginebra-master-makers-london-dry-gin-70-cl.html",
    available: true,
  },
  {
    id: 5,
    name: "Ish London Dry Gyn 70 cl.",
    description: "",
    tags: ["ginebra"],
    image: "./ish.jpeg",
    price: 10,
    comparePrice: 28,
    quantity: 1,
    urlComparePrice:
      "https://www.bodecall.com/destilados-y-licores/todos-los-destilados-y-licores/ish-detail",
    available: false,
  },
  {
    id: 6,
    name: "Sorel London Dry Gin 70 cl.",
    description: "",
    tags: ["ginebra"],
    image: "./sorel.jpeg",
    price: 6,
    comparePrice: 12,
    quantity: 1,
    urlComparePrice: "https://dmbrands.es/producto/sorel-london-dry-gin-70-cl/",
    available: true,
  },
  {
    id: 7,
    name: "Jägermeister 70 cl.",
    description: "",
    tags: ["licor"],
    image: "./jagermeister.jpeg",
    price: 6,
    comparePrice: 12,
    quantity: 1,
    urlComparePrice: "https://dmbrands.es/producto/sorel-london-dry-gin-70-cl/",
    available: false,
  },
  {
    id: 8,
    name: "Vermut Rojo Ancora de Silleiro",
    description: "Vermút Rojo Ancora de Silleiro, Gallego, colección de Autor",
    tags: ["Vermut"],
    image: "./ancora.jpeg",
    price: 4,
    comparePrice: 7.95,
    quantity: 4,
    urlComparePrice:
      "https://deliciasartesanas.com/es/vermuts/vermut-rojo-ancora-de-silleiro",
    available: false,
  },
];

export default products;
